/** Extra demo bank keyed by chapterKey. Safe to re-seed: unique fronts / questions. */

export type FlashSeed = {
  chapterKey: string;
  front: string;
  back: string;
  subject: string;
  topic: string;
  difficulty: string;
};

export type McqSeed = {
  chapterKey: string;
  question: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: string;
  explanation: string;
  subject: string;
  topic: string;
  difficulty: string;
};

export type ArticleSeed = {
  title: string;
  excerpt: string;
  body: string;
  tag: string;
  featured: boolean;
  imageUrl: string;
  /** Negative ms from now: 0 = now, -3h = 3 hours ago, etc. */
  publishedOffsetMs: number;
};

export const extraFlash: FlashSeed[] = [
  // Everyday Science
  {
    chapterKey: "everyday-science",
    front: "Why does a pressure cooker cook food faster?",
    back: "Higher pressure raises the boiling point of water, so food cooks at a higher temperature.",
    subject: "Science",
    topic: "Physics",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    front: "What does ORS stand for in first aid?",
    back: "Oral Rehydration Solution — a mix of salts and sugar used to treat dehydration.",
    subject: "Science",
    topic: "Health",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    front: "Which vitamin is synthesised in skin on exposure to sunlight?",
    back: "Vitamin D",
    subject: "Science",
    topic: "Biology",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    front: "Why is CNG preferred over petrol in city buses?",
    back: "It burns cleaner — fewer particulates and sulphur oxides — and is cheaper in many Indian cities.",
    subject: "Science",
    topic: "Environment",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    front: "What is pasteurisation?",
    back: "Heating milk or other liquids to kill harmful microbes without fully sterilising the product.",
    subject: "Science",
    topic: "Biology",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    front: "Which gas is filled in commercial food packets to keep chips crisp?",
    back: "Nitrogen — it is inert and displaces oxygen that would turn fats rancid.",
    subject: "Science",
    topic: "Chemistry",
    difficulty: "hard",
  },
  {
    chapterKey: "everyday-science",
    front: "What is the function of a catalytic converter in a vehicle?",
    back: "It converts toxic exhaust gases (CO, NOx, unburnt hydrocarbons) into less harmful CO₂, N₂ and water.",
    subject: "Science",
    topic: "Chemistry",
    difficulty: "hard",
  },
  {
    chapterKey: "everyday-science",
    front: "Why do we add iodine to common salt?",
    back: "To prevent iodine-deficiency disorders such as goitre — a public-health fortification measure.",
    subject: "Science",
    topic: "Health",
    difficulty: "easy",
  },

  // Indian Constitution
  {
    chapterKey: "indian-constitution",
    front: "When did the Constitution of India come into force?",
    back: "26 January 1950 — celebrated as Republic Day. It was adopted on 26 November 1949.",
    subject: "Polity",
    topic: "Constitution",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    front: "Who was the Chairman of the Drafting Committee?",
    back: "Dr B. R. Ambedkar",
    subject: "Polity",
    topic: "Constitution",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    front: "How many Schedules does the Constitution have at present?",
    back: "12 Schedules",
    subject: "Polity",
    topic: "Constitution",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    front: "Article 368 deals with?",
    back: "The procedure to amend the Constitution.",
    subject: "Polity",
    topic: "Amendment",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    front: "What is a Money Bill under Article 110?",
    back: "A bill dealing only with taxation, borrowing, or expenditure from the Consolidated Fund — certified by the Speaker.",
    subject: "Polity",
    topic: "Parliament",
    difficulty: "hard",
  },
  {
    chapterKey: "indian-constitution",
    front: "The idea of a Federation with a strong Centre was borrowed from?",
    back: "The Government of India Act, 1935 (and Canadian federalism for residual powers).",
    subject: "Polity",
    topic: "Sources",
    difficulty: "hard",
  },
  {
    chapterKey: "indian-constitution",
    front: "What does Article 32 provide?",
    back: "The right to move the Supreme Court for enforcement of Fundamental Rights — called the heart and soul of the Constitution by Ambedkar.",
    subject: "Polity",
    topic: "Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    front: "Who appoints the Chief Minister of a State?",
    back: "The Governor, normally the leader of the majority party or coalition in the Legislative Assembly.",
    subject: "Polity",
    topic: "States",
    difficulty: "easy",
  },

  // Fundamental Rights
  {
    chapterKey: "fundamental-rights",
    front: "Which Articles cover Fundamental Rights?",
    back: "Articles 12 to 35 in Part III.",
    subject: "Polity",
    topic: "Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "fundamental-rights",
    front: "Article 21 protects?",
    back: "Protection of life and personal liberty — expanded by courts to include privacy, livelihood, and a clean environment.",
    subject: "Polity",
    topic: "Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "fundamental-rights",
    front: "Which amendment added Fundamental Duties?",
    back: "42nd Amendment, 1976 — Part IVA, Article 51A. 86th Amendment later added the duty to educate children.",
    subject: "Polity",
    topic: "Duties",
    difficulty: "hard",
  },
  {
    chapterKey: "fundamental-rights",
    front: "Can Fundamental Rights be amended?",
    back: "Yes, by constitutional amendment, but not so as to damage the basic structure (Kesavananda Bharati).",
    subject: "Polity",
    topic: "Rights",
    difficulty: "hard",
  },
  {
    chapterKey: "fundamental-rights",
    front: "Article 17 abolishes?",
    back: "Untouchability — its practice in any form is an offence.",
    subject: "Polity",
    topic: "Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "fundamental-rights",
    front: "Writ of habeas corpus means?",
    back: "Produce the body — a court order to produce a detained person and justify the detention.",
    subject: "Polity",
    topic: "Writs",
    difficulty: "easy",
  },

  // Indian Economy
  {
    chapterKey: "indian-economy",
    front: "What is GDP?",
    back: "Gross Domestic Product — the market value of all final goods and services produced within a country in a period.",
    subject: "Economy",
    topic: "National income",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    front: "Repo rate is?",
    back: "The interest rate at which RBI lends short-term funds to commercial banks against securities.",
    subject: "Economy",
    topic: "Monetary policy",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    front: "What is fiscal deficit?",
    back: "The gap between the government's total expenditure and its total receipts excluding borrowings.",
    subject: "Economy",
    topic: "Fiscal policy",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    front: "GST was introduced in India in which year?",
    back: "2017 — a destination-based indirect tax subsuming most central and state levies on goods and services.",
    subject: "Economy",
    topic: "Taxation",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    front: "What does PM-KISAN provide?",
    back: "Income support of ₹6,000 a year to eligible farmer families, paid in three instalments.",
    subject: "Economy",
    topic: "Agriculture",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    front: "Headline vs core inflation?",
    back: "Headline includes food and fuel; core excludes them to show underlying price pressure.",
    subject: "Economy",
    topic: "Inflation",
    difficulty: "hard",
  },
  {
    chapterKey: "indian-economy",
    front: "What is a current account deficit?",
    back: "When a country's imports of goods, services, and transfers exceed exports — financed by capital inflows.",
    subject: "Economy",
    topic: "External sector",
    difficulty: "hard",
  },
  {
    chapterKey: "indian-economy",
    front: "NITI Aayog replaced?",
    back: "The Planning Commission, in 2015. It is a think-tank, not a fund-allocating body.",
    subject: "Economy",
    topic: "Institutions",
    difficulty: "easy",
  },

  // Ecology
  {
    chapterKey: "ecology-biodiversity",
    front: "What is a biodiversity hotspot?",
    back: "A region with exceptional endemic species that has lost a large share of its original habitat. India has four: Himalaya, Western Ghats, Indo-Burma, Sundaland (Nicobar).",
    subject: "Environment",
    topic: "Biodiversity",
    difficulty: "hard",
  },
  {
    chapterKey: "ecology-biodiversity",
    front: "Project Tiger was launched in?",
    back: "1973 — a centrally sponsored scheme to protect tigers and their habitats.",
    subject: "Environment",
    topic: "Conservation",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    front: "What is an ecological niche?",
    back: "The role and position of a species in its ecosystem — how it uses resources and interacts with others.",
    subject: "Environment",
    topic: "Ecology",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    front: "The Ramsar Convention deals with?",
    back: "Wetlands of international importance. India is a party and has many Ramsar sites.",
    subject: "Environment",
    topic: "Treaties",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    front: "What is biomagnification?",
    back: "Increase in concentration of a toxin as it moves up the food chain (e.g. DDT in birds).",
    subject: "Environment",
    topic: "Pollution",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    front: "CITES regulates?",
    back: "International trade in endangered species of wild fauna and flora.",
    subject: "Environment",
    topic: "Treaties",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    front: "What is a keystone species?",
    back: "A species whose effect on the ecosystem is disproportionately large relative to its abundance — e.g. tiger, fig trees.",
    subject: "Environment",
    topic: "Ecology",
    difficulty: "hard",
  },
  {
    chapterKey: "ecology-biodiversity",
    front: "National Green Tribunal was set up in?",
    back: "2010, under the NGT Act, for speedy disposal of environmental cases.",
    subject: "Environment",
    topic: "Institutions",
    difficulty: "easy",
  },

  // Modern India
  {
    chapterKey: "modern-india",
    front: "When was the Indian National Congress founded?",
    back: "1885, by A. O. Hume, with W. C. Bonnerjee as the first president.",
    subject: "History",
    topic: "National movement",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    front: "The partition of Bengal took place in?",
    back: "1905, under Lord Curzon; it was revoked in 1911.",
    subject: "History",
    topic: "National movement",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    front: "Jallianwala Bagh massacre year?",
    back: "1919, Amritsar — troops under General Dyer fired on an unarmed gathering.",
    subject: "History",
    topic: "National movement",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    front: "Non-Cooperation Movement was launched in?",
    back: "1920, after the Khilafat issue and Jallianwala Bagh, and withdrawn after Chauri Chaura (1922).",
    subject: "History",
    topic: "Gandhian movements",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    front: "What was the slogan of the Quit India Movement?",
    back: "Do or Die — given by Gandhi in 1942.",
    subject: "History",
    topic: "Gandhian movements",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    front: "Who wrote Hind Swaraj?",
    back: "M. K. Gandhi (1909) — a critique of modern civilisation and a case for swaraj.",
    subject: "History",
    topic: "Thought",
    difficulty: "hard",
  },
  {
    chapterKey: "modern-india",
    front: "The Cabinet Mission came to India in?",
    back: "1946 — it proposed a three-tier federation and a constituent assembly, but no Pakistan as a separate sovereign state.",
    subject: "History",
    topic: "Transfer of power",
    difficulty: "hard",
  },
  {
    chapterKey: "modern-india",
    front: "Who founded the Servants of India Society?",
    back: "Gopal Krishna Gokhale, in 1905.",
    subject: "History",
    topic: "Reformers",
    difficulty: "hard",
  },

  // NEET Physics
  {
    chapterKey: "neet-mechanics",
    front: "Newton's second law in equation form?",
    back: "F = dp/dt, or F = ma when mass is constant.",
    subject: "Physics",
    topic: "Laws of motion",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    front: "SI unit of momentum?",
    back: "kg·m/s",
    subject: "Physics",
    topic: "Kinematics",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    front: "Work done by a conservative force around a closed path?",
    back: "Zero — the force is path-independent.",
    subject: "Physics",
    topic: "Work-energy",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    front: "Dimensional formula of force?",
    back: "[M L T⁻²]",
    subject: "Physics",
    topic: "Units",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    front: "What is impulse?",
    back: "Change in momentum; equal to force × time for a constant force.",
    subject: "Physics",
    topic: "Laws of motion",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    front: "Escape velocity from Earth (approx.)?",
    back: "About 11.2 km/s from the surface, ignoring atmosphere and rotation.",
    subject: "Physics",
    topic: "Gravitation",
    difficulty: "hard",
  },

  // NEET Chemistry
  {
    chapterKey: "neet-atomic",
    front: "Atomic number is equal to?",
    back: "The number of protons in the nucleus.",
    subject: "Chemistry",
    topic: "Atomic structure",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-atomic",
    front: "Who proposed the planetary model of the atom?",
    back: "Rutherford, after the gold-foil experiment.",
    subject: "Chemistry",
    topic: "Atomic structure",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-atomic",
    front: "Pauli exclusion principle states?",
    back: "No two electrons in an atom can have the same set of four quantum numbers.",
    subject: "Chemistry",
    topic: "Electronic configuration",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-atomic",
    front: "Isotopes differ in?",
    back: "Mass number (neutrons), but have the same atomic number.",
    subject: "Chemistry",
    topic: "Atomic structure",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-atomic",
    front: "The azimuthal quantum number l determines?",
    back: "The shape of the orbital (s, p, d, f).",
    subject: "Chemistry",
    topic: "Quantum numbers",
    difficulty: "hard",
  },
  {
    chapterKey: "neet-atomic",
    front: "Heisenberg uncertainty principle?",
    back: "It is impossible to know both position and momentum of a particle with unlimited precision: Δx · Δp ≥ h/4π.",
    subject: "Chemistry",
    topic: "Quantum",
    difficulty: "hard",
  },

  // NEET Biology
  {
    chapterKey: "neet-physiology",
    front: "Where does gas exchange occur in the lungs?",
    back: "Alveoli — thin-walled sacs surrounded by capillaries.",
    subject: "Biology",
    topic: "Respiration",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    front: "Which chamber of the heart pumps blood to the body?",
    back: "Left ventricle, through the aorta.",
    subject: "Biology",
    topic: "Circulation",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    front: "Nephrons are the functional units of?",
    back: "The kidney — they filter blood and form urine.",
    subject: "Biology",
    topic: "Excretion",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    front: "Insulin is secreted by?",
    back: "β-cells of the islets of Langerhans in the pancreas.",
    subject: "Biology",
    topic: "Endocrine",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    front: "What is a synapse?",
    back: "The junction between two neurons (or a neuron and an effector) where a signal is transmitted.",
    subject: "Biology",
    topic: "Neural",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    front: "ADH primarily acts on?",
    back: "Collecting ducts of the kidney, increasing water reabsorption.",
    subject: "Biology",
    topic: "Excretion",
    difficulty: "hard",
  },
];

export const extraMcq: McqSeed[] = [
  {
    chapterKey: "everyday-science",
    question: "Washing soda used in laundry is chemically",
    optionA: "Sodium bicarbonate",
    optionB: "Sodium carbonate",
    optionC: "Calcium carbonate",
    optionD: "Potassium nitrate",
    correctOption: "B",
    explanation: "Washing soda is Na₂CO₃·10H₂O (sodium carbonate).",
    subject: "Science",
    topic: "Chemistry",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    question: "The device that converts AC to DC in a phone charger is a",
    optionA: "Transformer only",
    optionB: "Rectifier",
    optionC: "Capacitor only",
    optionD: "Inductor only",
    correctOption: "B",
    explanation: "A rectifier (often a diode bridge) converts alternating current to direct current.",
    subject: "Science",
    topic: "Physics",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    question: "Goitre is commonly associated with deficiency of",
    optionA: "Iron",
    optionB: "Iodine",
    optionC: "Calcium",
    optionD: "Vitamin C",
    correctOption: "B",
    explanation: "Iodine deficiency enlarges the thyroid gland (goitre).",
    subject: "Science",
    topic: "Health",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    question: "LED lamps are more efficient than incandescent bulbs mainly because they",
    optionA: "Emit more heat",
    optionB: "Convert a larger share of energy into visible light",
    optionC: "Work only on DC grids",
    optionD: "Need no semiconductor",
    correctOption: "B",
    explanation: "LEDs waste less energy as heat compared with filament lamps.",
    subject: "Science",
    topic: "Physics",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    question: "Bleaching powder used for disinfecting water is",
    optionA: "Calcium oxychloride",
    optionB: "Sodium chloride",
    optionC: "Calcium sulphate",
    optionD: "Potassium permanganate",
    correctOption: "A",
    explanation: "Bleaching powder is CaOCl₂, used as a disinfectant.",
    subject: "Science",
    topic: "Chemistry",
    difficulty: "hard",
  },
  {
    chapterKey: "everyday-science",
    question: "The pigment that makes leaves green and captures light is",
    optionA: "Carotene only",
    optionB: "Xanthophyll only",
    optionC: "Chlorophyll",
    optionD: "Anthocyanin",
    correctOption: "C",
    explanation: "Chlorophyll absorbs light for photosynthesis and reflects green wavelengths.",
    subject: "Science",
    topic: "Biology",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    question: "A fuse in a household circuit is meant to",
    optionA: "Increase voltage",
    optionB: "Store charge",
    optionC: "Break the circuit if current is too high",
    optionD: "Convert AC to DC",
    correctOption: "C",
    explanation: "The fuse wire melts at high current and protects wiring and appliances.",
    subject: "Science",
    topic: "Physics",
    difficulty: "easy",
  },
  {
    chapterKey: "everyday-science",
    question: "ORS for diarrhoea should contain, besides water,",
    optionA: "Only sugar",
    optionB: "Only salt",
    optionC: "Glucose and salts in a defined ratio",
    optionD: "Antibiotics only",
    correctOption: "C",
    explanation: "WHO-ORS uses glucose to help sodium (and water) absorption in the intestine.",
    subject: "Science",
    topic: "Health",
    difficulty: "hard",
  },

  {
    chapterKey: "indian-constitution",
    question: "The Constitution of India was adopted by the Constituent Assembly on",
    optionA: "15 August 1947",
    optionB: "26 January 1950",
    optionC: "26 November 1949",
    optionD: "9 December 1946",
    correctOption: "C",
    explanation: "Adopted 26 November 1949; commenced 26 January 1950.",
    subject: "Polity",
    topic: "Constitution",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    question: "The office of the Comptroller and Auditor General is provided in",
    optionA: "Article 76",
    optionB: "Article 148",
    optionC: "Article 280",
    optionD: "Article 324",
    correctOption: "B",
    explanation: "CAG is under Article 148; Attorney-General is 76; Finance Commission 280; Election Commission 324.",
    subject: "Polity",
    topic: "Institutions",
    difficulty: "hard",
  },
  {
    chapterKey: "indian-constitution",
    question: "Residuary powers of legislation in India vest in",
    optionA: "The States",
    optionB: "The Union",
    optionC: "Both equally",
    optionD: "The Supreme Court",
    correctOption: "B",
    explanation: "Article 248 and the Union List entry 97 give residuary powers to Parliament.",
    subject: "Polity",
    topic: "Federalism",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    question: "The President of India is elected by",
    optionA: "All adult citizens directly",
    optionB: "Lok Sabha only",
    optionC: "An electoral college of elected MPs and MLAs",
    optionD: "Rajya Sabha only",
    correctOption: "C",
    explanation: "Article 54: elected MPs of both Houses and elected MLAs of states (and Delhi, Puducherry).",
    subject: "Polity",
    topic: "Executive",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    question: "A constitutional amendment that changes the federal provisions generally requires",
    optionA: "Simple majority in Parliament",
    optionB: "Special majority in Parliament plus ratification by half the states",
    optionC: "Consent of all states",
    optionD: "A national referendum",
    correctOption: "B",
    explanation: "Article 368 proviso: certain federal clauses need special majority plus ratification by at least half the state legislatures.",
    subject: "Polity",
    topic: "Amendment",
    difficulty: "hard",
  },
  {
    chapterKey: "indian-constitution",
    question: "The idea of Directive Principles of State Policy was borrowed mainly from",
    optionA: "The US Constitution",
    optionB: "The Irish Constitution",
    optionC: "The Australian Constitution",
    optionD: "The Japanese Constitution",
    correctOption: "B",
    explanation: "DPSPs were inspired by the Irish Constitution of 1937.",
    subject: "Polity",
    topic: "Sources",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    question: "Which body is a permanent constitutional body?",
    optionA: "Finance Commission",
    optionB: "Election Commission of India",
    optionC: "Delimitation Commission",
    optionD: "National Development Council",
    correctOption: "B",
    explanation: "The Election Commission is a permanent constitutional body (Article 324). Finance Commission is constituted every five years.",
    subject: "Polity",
    topic: "Institutions",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-constitution",
    question: "The Ninth Schedule was added by the",
    optionA: "1st Amendment",
    optionB: "42nd Amendment",
    optionC: "44th Amendment",
    optionD: "73rd Amendment",
    correctOption: "A",
    explanation: "The First Amendment (1951) added the Ninth Schedule to protect land-reform laws from judicial review (later qualified in IR Coelho).",
    subject: "Polity",
    topic: "Amendment",
    difficulty: "hard",
  },

  {
    chapterKey: "fundamental-rights",
    question: "Which of the following is NOT a Fundamental Right today?",
    optionA: "Right to equality",
    optionB: "Right to freedom of religion",
    optionC: "Right to property",
    optionD: "Right against exploitation",
    correctOption: "C",
    explanation: "Right to property was removed from Part III by the 44th Amendment (1978) and is now a legal right under Article 300A.",
    subject: "Polity",
    topic: "Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "fundamental-rights",
    question: "The writ of mandamus is issued to",
    optionA: "Produce a detained person",
    optionB: "Command a public authority to perform a duty",
    optionC: "Quash an order of a lower court",
    optionD: "Enquire into the legality of a claim to public office",
    correctOption: "B",
    explanation: "Mandamus ('we command') directs a public official or body to do its legal duty.",
    subject: "Polity",
    topic: "Writs",
    difficulty: "easy",
  },
  {
    chapterKey: "fundamental-rights",
    question: "Article 15 prohibits discrimination on grounds of",
    optionA: "Religion, race, caste, sex, place of birth",
    optionB: "Only caste and religion",
    optionC: "Income and education",
    optionD: "Political affiliation",
    correctOption: "A",
    explanation: "Article 15(1) lists religion, race, caste, sex, and place of birth.",
    subject: "Polity",
    topic: "Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "fundamental-rights",
    question: "Freedom of speech under Article 19 can be restricted in the interest of",
    optionA: "Any reason the government chooses",
    optionB: "Sovereignty, public order, decency, and other grounds listed in 19(2)",
    optionC: "Only defamation",
    optionD: "Only contempt of court",
    correctOption: "B",
    explanation: "Article 19(2) lists specific reasonable-restriction grounds; it is not an open-ended power.",
    subject: "Polity",
    topic: "Rights",
    difficulty: "hard",
  },
  {
    chapterKey: "fundamental-rights",
    question: "Puttaswamy (2017) recognised the right to privacy as part of",
    optionA: "Article 14 only",
    optionB: "Article 19(1)(a) only",
    optionC: "Article 21 (and the broader liberty cluster)",
    optionD: "Directive Principles",
    correctOption: "C",
    explanation: "A nine-judge bench held privacy to be a fundamental right intrinsic to Article 21 (and related freedoms).",
    subject: "Polity",
    topic: "Rights",
    difficulty: "hard",
  },
  {
    chapterKey: "fundamental-rights",
    question: "Preventive detention is dealt with under",
    optionA: "Article 20",
    optionB: "Article 21 only",
    optionC: "Article 22",
    optionD: "Article 32",
    correctOption: "C",
    explanation: "Article 22 provides safeguards relating to arrest and also to preventive detention.",
    subject: "Polity",
    topic: "Rights",
    difficulty: "easy",
  },

  {
    chapterKey: "indian-economy",
    question: "The Monetary Policy Committee of India is chaired by",
    optionA: "The Finance Minister",
    optionB: "The RBI Governor",
    optionC: "The Chief Economic Adviser",
    optionD: "The NITI Aayog Vice Chairperson",
    correctOption: "B",
    explanation: "The RBI Governor chairs the six-member MPC that sets the policy repo rate.",
    subject: "Economy",
    topic: "Monetary policy",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    question: "India's inflation target under the current flexible inflation-targeting regime is",
    optionA: "2% ± 1%",
    optionB: "4% ± 2%",
    optionC: "6% with no band",
    optionD: "0% (price stability only)",
    correctOption: "B",
    explanation: "The target is 4% CPI with a tolerance band of 2% to 6%.",
    subject: "Economy",
    topic: "Inflation",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    question: "Which of the following is a direct tax?",
    optionA: "GST",
    optionB: "Customs duty",
    optionC: "Corporation tax",
    optionD: "Excise on petrol (as a levy on goods)",
    correctOption: "C",
    explanation: "Corporation tax is levied on income/profits of companies — a direct tax. GST and customs are indirect.",
    subject: "Economy",
    topic: "Taxation",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    question: "Disinvestment in the Indian budget typically refers to",
    optionA: "Printing more currency",
    optionB: "Sale of government's equity in PSUs",
    optionC: "Cutting repo rate",
    optionD: "Raising MSP",
    correctOption: "B",
    explanation: "Disinvestment is reducing government shareholding in public sector enterprises.",
    subject: "Economy",
    topic: "Fiscal policy",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    question: "The base year currently used for India's GDP (as commonly cited in recent years) is",
    optionA: "2004-05",
    optionB: "2011-12",
    optionC: "1999-2000",
    optionD: "2017-18",
    correctOption: "B",
    explanation: "National accounts with 2011-12 as base year have been in use (a revision cycle is separately underway).",
    subject: "Economy",
    topic: "National income",
    difficulty: "hard",
  },
  {
    chapterKey: "indian-economy",
    question: "Which statement about UPI is correct?",
    optionA: "It is a cryptocurrency issued by RBI",
    optionB: "It is a real-time payment system built on IMPS, operated by NPCI",
    optionC: "It replaces RTGS for all wholesale settlements",
    optionD: "It is a stock-market clearing house",
    correctOption: "B",
    explanation: "UPI is NPCI's unified payments interface for instant bank-to-bank transfers.",
    subject: "Economy",
    topic: "Payments",
    difficulty: "easy",
  },
  {
    chapterKey: "indian-economy",
    question: "A regressive tax is one where",
    optionA: "The rate rises with income",
    optionB: "The poor pay a higher share of their income than the rich",
    optionC: "Only companies pay",
    optionD: "There is no collection cost",
    correctOption: "B",
    explanation: "Regressive taxes take a larger fraction of income from lower-income households (e.g. some consumption taxes).",
    subject: "Economy",
    topic: "Taxation",
    difficulty: "hard",
  },
  {
    chapterKey: "indian-economy",
    question: "FRBM Act is primarily concerned with",
    optionA: "Banking regulation",
    optionB: "Fiscal deficit and government debt discipline",
    optionC: "SEBI's IPO rules",
    optionD: "Agricultural MSP",
    correctOption: "B",
    explanation: "The Fiscal Responsibility and Budget Management Act sets a framework for deficit and debt.",
    subject: "Economy",
    topic: "Fiscal policy",
    difficulty: "easy",
  },

  {
    chapterKey: "ecology-biodiversity",
    question: "The Wildlife (Protection) Act was enacted in",
    optionA: "1972",
    optionB: "1981",
    optionC: "1986",
    optionD: "2002",
    correctOption: "A",
    explanation: "The Wildlife (Protection) Act, 1972, is the principal law for wildlife conservation in India.",
    subject: "Environment",
    topic: "Laws",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    question: "Kaziranga National Park is primarily known for conserving",
    optionA: "Asiatic lion",
    optionB: "One-horned rhinoceros",
    optionC: "Snow leopard",
    optionD: "Olive ridley turtle",
    correctOption: "B",
    explanation: "Kaziranga (Assam) is famous for the greater one-horned rhinoceros.",
    subject: "Environment",
    topic: "Protected areas",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    question: "The Montreal Protocol is associated with",
    optionA: "Wetland conservation",
    optionB: "Ozone-depleting substances",
    optionC: "Desertification",
    optionD: "Mercury pollution",
    correctOption: "B",
    explanation: "Montreal Protocol (1987) phases out CFCs and other ozone-depleting substances; Kigali Amendment added HFCs.",
    subject: "Environment",
    topic: "Treaties",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    question: "In an ecological pyramid of energy, energy",
    optionA: "Increases at each trophic level",
    optionB: "Stays constant",
    optionC: "Decreases at each successive trophic level",
    optionD: "Is undefined for aquatic systems",
    correctOption: "C",
    explanation: "Only a fraction of energy is transferred up; pyramids of energy are always upright.",
    subject: "Environment",
    topic: "Ecology",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    question: "Coral bleaching is mainly caused by",
    optionA: "Excess nitrogen in soil",
    optionB: "Expulsion of symbiotic zooxanthellae under stress (often heat)",
    optionC: "Overfishing of tuna only",
    optionD: "Volcanic ash exclusively",
    correctOption: "B",
    explanation: "Warmth and other stressors make corals expel algae, turning them white and reducing energy supply.",
    subject: "Environment",
    topic: "Climate",
    difficulty: "hard",
  },
  {
    chapterKey: "ecology-biodiversity",
    question: "The UNFCCC's Conference of Parties (COP) is",
    optionA: "A biodiversity treaty secretariat only",
    optionB: "The supreme decision-making body of the climate convention",
    optionC: "India's forest service exam",
    optionD: "A WTO dispute panel",
    correctOption: "B",
    explanation: "COP is the annual (typically) meeting of parties to the UN Framework Convention on Climate Change.",
    subject: "Environment",
    topic: "Climate",
    difficulty: "easy",
  },
  {
    chapterKey: "ecology-biodiversity",
    question: "Which gas has the highest share in India's anthropogenic GHG emissions?",
    optionA: "Methane",
    optionB: "Nitrous oxide",
    optionC: "Carbon dioxide",
    optionD: "SF₆",
    correctOption: "C",
    explanation: "CO₂ from energy and industry dominates India's GHG inventory; methane is significant but smaller.",
    subject: "Environment",
    topic: "Climate",
    difficulty: "hard",
  },
  {
    chapterKey: "ecology-biodiversity",
    question: "Biosphere reserves in India are designated under",
    optionA: "Only the Ramsar Convention",
    optionB: "UNESCO's Man and the Biosphere Programme (among other domestic notifications)",
    optionC: "CITES exclusively",
    optionD: "The Antarctic Treaty",
    correctOption: "B",
    explanation: "Many Indian biosphere reserves are under UNESCO MAB; they are also notified nationally.",
    subject: "Environment",
    topic: "Conservation",
    difficulty: "easy",
  },

  {
    chapterKey: "modern-india",
    question: "The founder of the Arya Samaj was",
    optionA: "Raja Ram Mohan Roy",
    optionB: "Swami Dayanand Saraswati",
    optionC: "Swami Vivekananda",
    optionD: "Jyotiba Phule",
    correctOption: "B",
    explanation: "Dayanand Saraswati founded Arya Samaj in 1875. Roy is associated with Brahmo Samaj.",
    subject: "History",
    topic: "Reformers",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    question: "The Lucknow Pact (1916) was an agreement between",
    optionA: "Congress and the Muslim League",
    optionB: "Congress and the British Cabinet",
    optionC: "Gandhi and Ambedkar",
    optionD: "Moderates and the INA",
    correctOption: "A",
    explanation: "Congress and the League agreed on constitutional reforms and representation.",
    subject: "History",
    topic: "National movement",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    question: "Who gave the slogan 'Inquilab Zindabad'?",
    optionA: "Bhagat Singh (popularised; coined by Hasrat Mohani)",
    optionB: "Subhas Chandra Bose only",
    optionC: "Bal Gangadhar Tilak",
    optionD: "Lala Lajpat Rai",
    correctOption: "A",
    explanation: "Hasrat Mohani coined it; Bhagat Singh and HSRA popularised it.",
    subject: "History",
    topic: "Revolutionaries",
    difficulty: "hard",
  },
  {
    chapterKey: "modern-india",
    question: "The Poona Pact (1932) was signed between",
    optionA: "Gandhi and Irwin",
    optionB: "Gandhi and Ambedkar",
    optionC: "Nehru and Jinnah",
    optionD: "Bose and Gandhi",
    correctOption: "B",
    explanation: "It replaced separate electorates for Depressed Classes with reserved seats in a joint electorate.",
    subject: "History",
    topic: "National movement",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    question: "The INA trials were held at",
    optionA: "Cellular Jail",
    optionB: "Red Fort, Delhi",
    optionC: "Lahore Fort",
    optionD: "Aga Khan Palace",
    correctOption: "B",
    explanation: "The INA officers' trials at the Red Fort (1945–46) sparked nationwide protest.",
    subject: "History",
    topic: "Transfer of power",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    question: "Who started the newspaper Kesari?",
    optionA: "Gopal Krishna Gokhale",
    optionB: "Bal Gangadhar Tilak",
    optionC: "Surendranath Banerjee",
    optionD: "Annie Besant",
    correctOption: "B",
    explanation: "Tilak started Kesari (Marathi) and also associated with Mahratta (English).",
    subject: "History",
    topic: "Press",
    difficulty: "easy",
  },
  {
    chapterKey: "modern-india",
    question: "The Cripps Mission (1942) offered India",
    optionA: "Immediate complete independence",
    optionB: "Dominion status after the war, with a constituent assembly",
    optionC: "A separate Pakistan at once",
    optionD: "UN trusteeship",
    correctOption: "B",
    explanation: "Cripps proposed post-war dominion status and a constitution-making body; Congress rejected it.",
    subject: "History",
    topic: "Transfer of power",
    difficulty: "hard",
  },
  {
    chapterKey: "modern-india",
    question: "The Ilbert Bill controversy (1883) was about",
    optionA: "Salt tax",
    optionB: "Indian judges trying European British subjects in criminal cases",
    optionC: "Partition of Bengal",
    optionD: "Factory working hours",
    correctOption: "B",
    explanation: "European opposition to Indian judges trying Europeans revealed racial bias in colonial justice.",
    subject: "History",
    topic: "Colonial policy",
    difficulty: "hard",
  },

  {
    chapterKey: "neet-mechanics",
    question: "A body moving with uniform velocity has",
    optionA: "Zero acceleration",
    optionB: "Constant non-zero acceleration",
    optionC: "Increasing momentum always",
    optionD: "Zero momentum",
    correctOption: "A",
    explanation: "Uniform velocity means acceleration is zero (in a given inertial frame).",
    subject: "Physics",
    topic: "Kinematics",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    question: "The area under a force–time graph gives",
    optionA: "Power",
    optionB: "Impulse",
    optionC: "Work",
    optionD: "Energy",
    correctOption: "B",
    explanation: "Impulse = ∫F dt, which is the area under an F–t curve.",
    subject: "Physics",
    topic: "Laws of motion",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    question: "If the net force on a particle is zero, its",
    optionA: "Velocity must be zero",
    optionB: "Acceleration is zero (momentum is constant)",
    optionC: "Kinetic energy must be zero",
    optionD: "Position is at the origin",
    correctOption: "B",
    explanation: "Newton's first law: zero net force ⇒ constant velocity, not necessarily rest.",
    subject: "Physics",
    topic: "Laws of motion",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    question: "Work done by friction on a sliding block is generally",
    optionA: "Always positive",
    optionB: "Negative (it dissipates mechanical energy)",
    optionC: "Always zero",
    optionD: "Independent of displacement",
    correctOption: "B",
    explanation: "Kinetic friction opposes displacement, so W = F·s is negative.",
    subject: "Physics",
    topic: "Work-energy",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-mechanics",
    question: "The acceleration due to gravity is maximum at",
    optionA: "The equator on Earth's surface",
    optionB: "The poles on Earth's surface (among surface points)",
    optionC: "The centre of the Earth",
    optionD: "Geostationary orbit",
    correctOption: "B",
    explanation: "g is larger at poles than equator due to rotation and Earth's oblateness; at the centre g is zero.",
    subject: "Physics",
    topic: "Gravitation",
    difficulty: "hard",
  },
  {
    chapterKey: "neet-mechanics",
    question: "A satellite in a circular orbit has total energy that is",
    optionA: "Positive",
    optionB: "Zero",
    optionC: "Negative",
    optionD: "Infinite",
    correctOption: "C",
    explanation: "Bound orbits have negative total energy (E = −GMm/2r for a circular orbit).",
    subject: "Physics",
    topic: "Gravitation",
    difficulty: "hard",
  },

  {
    chapterKey: "neet-atomic",
    question: "The number of electrons in a neutral atom of ¹²C is",
    optionA: "6",
    optionB: "12",
    optionC: "18",
    optionD: "4",
    correctOption: "A",
    explanation: "Atomic number of carbon is 6; a neutral atom has 6 electrons.",
    subject: "Chemistry",
    topic: "Atomic structure",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-atomic",
    question: "The maximum number of electrons in a p subshell is",
    optionA: "2",
    optionB: "6",
    optionC: "10",
    optionD: "14",
    correctOption: "B",
    explanation: "Three p orbitals × 2 electrons = 6.",
    subject: "Chemistry",
    topic: "Electronic configuration",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-atomic",
    question: "Cathode rays are",
    optionA: "Protons",
    optionB: "Neutrons",
    optionC: "Electrons",
    optionD: "Alpha particles",
    correctOption: "C",
    explanation: "J. J. Thomson identified cathode rays as electrons.",
    subject: "Chemistry",
    topic: "Atomic structure",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-atomic",
    question: "The energy of an electron in a hydrogen atom is more negative when n is",
    optionA: "Larger",
    optionB: "Smaller",
    optionC: "Equal to l",
    optionD: "Undefined",
    correctOption: "B",
    explanation: "E_n = −13.6/n² eV; smaller n means more tightly bound (more negative energy).",
    subject: "Chemistry",
    topic: "Bohr model",
    difficulty: "hard",
  },
  {
    chapterKey: "neet-atomic",
    question: "Hund's rule is concerned with",
    optionA: "Filling orbitals of equal energy with unpaired electrons first",
    optionB: "Nuclear stability",
    optionC: "Radioactive decay series",
    optionD: "Ideal gas constant",
    correctOption: "A",
    explanation: "Electrons occupy degenerate orbitals singly with parallel spins before pairing.",
    subject: "Chemistry",
    topic: "Electronic configuration",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-atomic",
    question: "The dual nature of matter was proposed by",
    optionA: "Planck",
    optionB: "de Broglie",
    optionC: "Bohr",
    optionD: "Dalton",
    correctOption: "B",
    explanation: "Louis de Broglie suggested that particles have wave nature, λ = h/p.",
    subject: "Chemistry",
    topic: "Quantum",
    difficulty: "easy",
  },

  {
    chapterKey: "neet-physiology",
    question: "The pacemaker of the human heart is the",
    optionA: "AV node",
    optionB: "SA node",
    optionC: "Purkinje fibres",
    optionD: "Bundle of His",
    correctOption: "B",
    explanation: "The sino-atrial node initiates the heartbeat.",
    subject: "Biology",
    topic: "Circulation",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    question: "Oxygen is mainly transported in blood",
    optionA: "Dissolved only in plasma",
    optionB: "Bound to haemoglobin in RBCs",
    optionC: "As carbonic acid",
    optionD: "Bound to albumin",
    correctOption: "B",
    explanation: "Most O₂ is carried as oxyhaemoglobin; a small fraction is dissolved.",
    subject: "Biology",
    topic: "Respiration",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    question: "Bile is produced by the",
    optionA: "Pancreas",
    optionB: "Gall bladder",
    optionC: "Liver",
    optionD: "Spleen",
    correctOption: "C",
    explanation: "Hepatocytes produce bile; the gall bladder stores and concentrates it.",
    subject: "Biology",
    topic: "Digestion",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    question: "Which hormone lowers blood glucose?",
    optionA: "Glucagon",
    optionB: "Insulin",
    optionC: "Cortisol",
    optionD: "Adrenaline",
    correctOption: "B",
    explanation: "Insulin promotes glucose uptake and storage; glucagon raises blood sugar.",
    subject: "Biology",
    topic: "Endocrine",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    question: "The functional unit of contraction in skeletal muscle is the",
    optionA: "Neuron",
    optionB: "Sarcomere",
    optionC: "Nephron",
    optionD: "Alveolus",
    correctOption: "B",
    explanation: "A sarcomere is the segment between two Z-lines where actin–myosin sliding occurs.",
    subject: "Biology",
    topic: "Locomotion",
    difficulty: "easy",
  },
  {
    chapterKey: "neet-physiology",
    question: "Bowman's capsule is part of the",
    optionA: "Nephron",
    optionB: "Alveolus",
    optionC: "Neuron",
    optionD: "Villus",
    correctOption: "A",
    explanation: "Bowman's capsule plus glomerulus form the renal corpuscle of a nephron.",
    subject: "Biology",
    topic: "Excretion",
    difficulty: "easy",
  },
];

/** Named demo books (Phase P). Unique fronts/questions so re-seed is safe. */
export const demoFlash: FlashSeed[] = [
  {
    chapterKey: "lax-rights",
    front: "Which article of the Constitution deals with equality before law?",
    back: "Article 14.",
    subject: "Polity",
    topic: "Fundamental Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "lax-rights",
    front: "What is a writ of habeas corpus?",
    back: "An order to produce a detained person before a court and justify the detention.",
    subject: "Polity",
    topic: "Fundamental Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "lax-parliament",
    front: "What is the maximum gap allowed between two sessions of Parliament?",
    back: "Six months.",
    subject: "Polity",
    topic: "Parliament",
    difficulty: "easy",
  },
  {
    chapterKey: "spectrum-1857",
    front: "Where did the Revolt of 1857 begin among sepoys?",
    back: "Meerut, May 1857.",
    subject: "History",
    topic: "Revolt of 1857",
    difficulty: "easy",
  },
  {
    chapterKey: "spectrum-gandhi",
    front: "Which movement did Gandhi launch after the Rowlatt Act?",
    back: "The Rowlatt Satyagraha (1919).",
    subject: "History",
    topic: "Gandhian Era",
    difficulty: "easy",
  },
  {
    chapterKey: "hcv-newton",
    front: "State Newton's second law in momentum form.",
    back: "Force equals the rate of change of momentum: F = dp/dt.",
    subject: "Physics",
    topic: "Newton's Laws",
    difficulty: "easy",
  },
  {
    chapterKey: "hcv-energy",
    front: "What is the SI unit of work?",
    back: "Joule (N·m).",
    subject: "Physics",
    topic: "Work and Energy",
    difficulty: "easy",
  },
];

export const demoMcq: McqSeed[] = [
  {
    chapterKey: "lax-rights",
    question: "Article 32 of the Constitution is described as the heart and soul of the Constitution because it",
    optionA: "Creates the Rajya Sabha",
    optionB: "Guarantees the right to move the Supreme Court for enforcement of Fundamental Rights",
    optionC: "Lists the Directive Principles",
    optionD: "Defines the Union List",
    correctOption: "B",
    explanation: "Article 32 gives original jurisdiction to the Supreme Court to enforce Fundamental Rights — Dr Ambedkar called it the heart and soul.",
    subject: "Polity",
    topic: "Fundamental Rights",
    difficulty: "easy",
  },
  {
    chapterKey: "lax-rights",
    question: "Reasonable restrictions on the freedom of speech under Article 19(2) may be imposed in the interest of",
    optionA: "Only defamation",
    optionB: "Sovereignty and integrity of India, public order, and other grounds listed in 19(2)",
    optionC: "Any ground the state chooses by ordinance",
    optionD: "Cabinet convenience",
    correctOption: "B",
    explanation: "Article 19(2) enumerates the grounds; restrictions must be reasonable and fall within those heads.",
    subject: "Polity",
    topic: "Fundamental Rights",
    difficulty: "medium",
  },
  {
    chapterKey: "lax-rights",
    question: "Which writ is typically used to quash an order of a body that acted without jurisdiction?",
    optionA: "Habeas corpus",
    optionB: "Mandamus",
    optionC: "Certiorari",
    optionD: "Quo warranto",
    correctOption: "C",
    explanation: "Certiorari is used to quash a decision of a lower court or tribunal that acted without or in excess of jurisdiction.",
    subject: "Polity",
    topic: "Fundamental Rights",
    difficulty: "medium",
  },
  {
    chapterKey: "lax-parliament",
    question: "A Money Bill can be introduced only in the",
    optionA: "Rajya Sabha",
    optionB: "Lok Sabha",
    optionC: "Joint sitting",
    optionD: "Either House with the President's prior nod only in Rajya Sabha",
    correctOption: "B",
    explanation: "Article 110 Money Bills originate only in the Lok Sabha, and only on the President's recommendation.",
    subject: "Polity",
    topic: "Parliament",
    difficulty: "easy",
  },
  {
    chapterKey: "lax-parliament",
    question: "The Rajya Sabha can delay a Money Bill by a maximum of",
    optionA: "14 days",
    optionB: "30 days",
    optionC: "Six months",
    optionD: "It can reject the Bill",
    correctOption: "A",
    explanation: "Rajya Sabha must return a Money Bill within 14 days; it cannot reject it.",
    subject: "Polity",
    topic: "Parliament",
    difficulty: "easy",
  },
  {
    chapterKey: "spectrum-1857",
    question: "Which of the following was a political cause of the Revolt of 1857?",
    optionA: "Doctrine of Lapse and annexation of states",
    optionB: "Discovery of oil in Assam",
    optionC: "Introduction of GST",
    optionD: "Partition of Bengal in 1905",
    correctOption: "A",
    explanation: "Dalhousie's Doctrine of Lapse and annexations (e.g. Awadh) alienated Indian rulers and were a major political cause.",
    subject: "History",
    topic: "Revolt of 1857",
    difficulty: "easy",
  },
  {
    chapterKey: "spectrum-1857",
    question: "Bahadur Shah Zafar was declared the symbolic leader of the 1857 revolt at",
    optionA: "Lucknow",
    optionB: "Delhi",
    optionC: "Kanpur",
    optionD: "Jhansi",
    correctOption: "B",
    explanation: "Rebels in Delhi proclaimed the Mughal emperor as the nominal head of the uprising.",
    subject: "History",
    topic: "Revolt of 1857",
    difficulty: "easy",
  },
  {
    chapterKey: "spectrum-gandhi",
    question: "The Non-Cooperation Movement was withdrawn by Gandhi after",
    optionA: "The Chauri Chaura violence (1922)",
    optionB: "The Dandi March",
    optionC: "The Cripps Mission",
    optionD: "Quit India being declared illegal",
    correctOption: "A",
    explanation: "After the Chauri Chaura incident, Gandhi called off Non-Cooperation, arguing the country was not ready for non-violent mass action.",
    subject: "History",
    topic: "Gandhian Era",
    difficulty: "easy",
  },
  {
    chapterKey: "spectrum-gandhi",
    question: "The Salt Satyagraha (Dandi March) began in",
    optionA: "1919",
    optionB: "1920",
    optionC: "1930",
    optionD: "1942",
    correctOption: "C",
    explanation: "Gandhi marched from Sabarmati to Dandi in 1930 to break the salt law, launching Civil Disobedience.",
    subject: "History",
    topic: "Gandhian Era",
    difficulty: "easy",
  },
  {
    chapterKey: "hcv-newton",
    question: "A body of mass 2 kg is acted on by a net force of 10 N. Its acceleration is",
    optionA: "2 m/s²",
    optionB: "5 m/s²",
    optionC: "10 m/s²",
    optionD: "20 m/s²",
    correctOption: "B",
    explanation: "a = F/m = 10/2 = 5 m/s².",
    subject: "Physics",
    topic: "Newton's Laws",
    difficulty: "easy",
  },
  {
    chapterKey: "hcv-newton",
    question: "If the net external force on a system is zero, the system's linear momentum",
    optionA: "Must be zero",
    optionB: "Is conserved",
    optionC: "Increases linearly with time",
    optionD: "Depends only on potential energy",
    correctOption: "B",
    explanation: "Newton's first law / conservation of momentum: F_net = dp/dt = 0 implies p is constant.",
    subject: "Physics",
    topic: "Newton's Laws",
    difficulty: "easy",
  },
  {
    chapterKey: "hcv-newton",
    question: "Action and reaction forces (Newton's third law)",
    optionA: "Act on the same body and cancel",
    optionB: "Act on different bodies and do not cancel as a pair on one body",
    optionC: "Exist only in gravity",
    optionD: "Are always frictional",
    correctOption: "B",
    explanation: "The two forces of a pair act on two different bodies, so they do not cancel on a single free-body diagram.",
    subject: "Physics",
    topic: "Newton's Laws",
    difficulty: "medium",
  },
  {
    chapterKey: "hcv-energy",
    question: "Work done by a constant force F through displacement s is maximum when the angle between F and s is",
    optionA: "90°",
    optionB: "180°",
    optionC: "0°",
    optionD: "45°",
    correctOption: "C",
    explanation: "W = Fs cosθ is maximum when cosθ = 1, i.e. θ = 0°.",
    subject: "Physics",
    topic: "Work and Energy",
    difficulty: "easy",
  },
  {
    chapterKey: "hcv-energy",
    question: "A 1 kg mass falls freely through 5 m. The kinetic energy gained (take g = 10 m/s²), ignoring air resistance, is",
    optionA: "5 J",
    optionB: "10 J",
    optionC: "50 J",
    optionD: "100 J",
    correctOption: "C",
    explanation: "Loss in PE = mgh = 1×10×5 = 50 J, which appears as KE.",
    subject: "Physics",
    topic: "Work and Energy",
    difficulty: "easy",
  },
];

export const extraArticles: ArticleSeed[] = [
  {
    title: "Heat Islands and Indian Cities: Why Night Temperatures Stay High",
    excerpt:
      "Concrete, traffic, and lost tree cover trap heat after sunset. A GS Paper III brief on urban climate risk.",
    body: `Urban heat islands form when built surfaces absorb solar energy by day and release it slowly at night. Indian metros often record night-time temperatures several degrees above nearby rural stations.

For prelims: remember albedo, evapotranspiration from trees, and the role of waste heat from ACs and vehicles. For mains, pair this with Heat Action Plans, cool roofs, and the National Disaster Management Authority's guidance on heatwaves.

Use examples — Ahmedabad's heat action plan, bus-stop shading, and ward-level cooling centres — to show governance, not just physics.`,
    tag: "Environment",
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?auto=format&fit=crop&w=1200&q=80",
    publishedOffsetMs: -35 * 60 * 1000,
  },
  {
    title: "ISRO, Space Economy, and the IN-SPACe Opening",
    excerpt:
      "Private launch services and satellite comms are no longer a PSU-only story. Map the institutional stack for GS III.",
    body: `IN-SPACe authorises non-government entities; NSIL commercialises ISRO's hardware; DOS remains the policy parent. The Indian Space Policy 2023 sketches roles without a full statute yet.

Prelims hooks: Gaganyaan, SSLV vs PSLV, NavIC, and Aditya-L1. Mains: strategic autonomy in PNT, earth observation for agriculture and disaster management, and export controls.

Keep the tone factual: India is a capable launch state still building a deep private supply chain.`,
    tag: "ScienceTech",
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?auto=format&fit=crop&w=1200&q=80",
    publishedOffsetMs: -3 * 60 * 60 * 1000,
  },
  {
    title: "MSP, Price Deficiency, and the Politics of Procurement",
    excerpt:
      "Minimum support prices sit at the junction of food security, fiscal cost, and crop diversification.",
    body: `MSP is announced for mandated crops on CACP advice. Effective MSP, however, is what FCI and state agencies actually buy — concentrated in paddy and wheat in a few states.

Alternatives: price deficiency payments (Bhavantar), income support (PM-KISAN), and futures markets. Each has leakage and delay risks.

For ethics and GS III, weigh farmer income against consumer inflation, groundwater stress in paddy belts, and WTO amber-box debates.`,
    tag: "Economy",
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1200&q=80",
    publishedOffsetMs: -2 * 24 * 60 * 60 * 1000,
  },
  {
    title: "India's Semiconductor Mission: Fabs, ATMP, and Design",
    excerpt:
      "Incentives target fabrication, assembly, and chip design. A compact brief for Science & Tech plus Economy.",
    body: `The India Semiconductor Mission offers fiscal support for fabs, display units, and ATMP/OSAT plants, plus a design-linked incentive for startups.

Why it matters: chips are dual-use, supply chains snapped during COVID, and AI demand is rising. Constraints include water, ultra-pure chemicals, talent, and multi-year construction.

Compare with Taiwan and the US CHIPS Act without copying talking points — stress ecosystem (EDA tools, equipment, offtake) rather than a single factory.`,
    tag: "ScienceTech",
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    publishedOffsetMs: -3 * 24 * 60 * 60 * 1000,
  },
  {
    title: "UNESCO Heritage and Cultural Diplomacy from India",
    excerpt:
      "Inscriptions are not just tourism plaques — they are foreign-policy and conservation stories.",
    body: `World Heritage listing under UNESCO's 1972 Convention requires outstanding universal value, integrity, and a management plan. India has a long tentative list and a mix of cultural and natural sites.

Recent debates include living heritage versus monument-centric conservation, and how pilgrimage towns handle visitor load.

Use this in GS I (culture) and GS II (soft power, UNESCO). Mention ASI, state archaeology, and community stewardship.`,
    tag: "Culture",
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80",
    publishedOffsetMs: -4 * 24 * 60 * 60 * 1000,
  },
  {
    title: "FR versus DPSP: The Classic Tension, Still Useful",
    excerpt:
      "An archive revision of Champakam Dorairajan through Minerva Mills — how courts balanced rights and welfare.",
    body: `Early on, Fundamental Rights prevailed over Directive Principles (Champakam). The 25th Amendment and Article 31C tried to shield certain DPSP laws. Minerva Mills restored a balance: DPSPs cannot destroy the essential features of Part III.

For answers: neither column is ornamental. Rights without material conditions ring hollow; welfare without justiciable rights invites excess.

Keep Kesavananda in the same revision cluster as 31C and the Ninth Schedule (IR Coelho).`,
    tag: "Polity",
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80",
    publishedOffsetMs: -14 * 24 * 60 * 60 * 1000,
  },
  {
    title: "Kigali Amendment: Cooling the Cooling Sector",
    excerpt:
      "HFCs replaced CFCs but warm the planet. Kigali phases them down under the Montreal Protocol's machinery.",
    body: `The Kigali Amendment (2016) adds hydrofluorocarbons to the Montreal Protocol's control regime. India ratified and has a later freeze/reduction schedule than some developed parties.

Prelims: Montreal vs Kyoto/Paris (ozone vs climate, different legal families). Mains: energy-efficient ACs, the cooling action plan, and industry transition costs.

This is a high-yield environment snippet because it links ozone heritage with climate mitigation.`,
    tag: "Environment",
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=1200&q=80",
    publishedOffsetMs: -16 * 24 * 60 * 60 * 1000,
  },
  {
    title: "Cabinet Mission, 1946: Why the Grouping Plan Failed",
    excerpt:
      "Archive history: a three-tier federation that almost avoided Partition — and why it did not.",
    body: `The Cabinet Mission proposed a union for defence, foreign affairs, and communications; provinces grouped in three sections; a constituent assembly. It rejected a sovereign Pakistan.

Congress and the League accepted in conflicting senses — especially over whether grouping was optional. Interim-government politics then collapsed the compromise.

Revise alongside Cripps (1942), Wavell Plan, and Mountbatten's 3 June plan. Useful for Modern India chronology questions.`,
    tag: "History",
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80",
    publishedOffsetMs: -20 * 24 * 60 * 60 * 1000,
  },
];
